package com.vltbr.minidrone.world;

/**
 * An axis-aligned training field the operator can define by hand.
 *
 * <p>One Minecraft block is one metre, so a field is a rectangle of block columns:
 * {@code minX..maxX} by {@code minZ..maxZ} on the surface layer {@code topY}. The
 * operator may describe it as two opposite corners, as a centre plus a size, or by
 * placing marker blocks; all three produce the same record, and the record is what
 * the mod advertises as {@code field_size_m} and what the virtual world origin is
 * computed from.
 *
 * <p>Coordinates are in <em>block centres</em> (a block at block coordinate
 * {@code i} has its centre at {@code i + 0.5}), which keeps an even-sized field
 * describable without rounding its centre onto a block edge. The footprint fields
 * ({@code minX}, {@code maxX}, ...) stay integers because they name blocks.
 *
 * <p>The origin - the point where {@code LOCAL_POSITION_NED} is (0, 0, 0) - is the
 * field centre by default, and the {@link OriginMode#CORNER} and
 * {@link OriginMode#EXPLICIT} modes let an operator put it somewhere else (a real
 * marker room, for instance, often has its motion-capture origin in a corner).
 * When it is not the centre, {@link #centerOffsetM()} tells the monitoring side
 * where the field sits relative to the origin, because the main project draws the
 * field around the origin otherwise.
 */
public record TrainingFieldDefinition(
    int minX,
    int minZ,
    int maxX,
    int maxZ,
    int topY,
    double originX,
    double originZ,
    OriginMode originMode,
    Source source
) {
    /** Where the operator's manual field came from. */
    public enum Source {
        /** Generated by {@code /minidrone arena create}. */
        ARENA,
        /** Two opposite corner coordinates. */
        CORNERS,
        /** A centre coordinate plus width and depth. */
        CENTRE_AND_SIZE,
        /** Placed corner/centre marker blocks. */
        MARKERS,
        /** Points recorded with the field selector item. */
        SELECTOR
    }

    /** How the origin was chosen. */
    public enum OriginMode {
        /** The geometric centre of the field (the default). */
        CENTRE,
        /** The centre of the {@code minX}/{@code minZ} corner block. */
        CORNER,
        /** A point the operator named explicitly. */
        EXPLICIT
    }

    public static final int MIN_SIZE_M = 1;
    public static final int MAX_SIZE_M = 256;

    public TrainingFieldDefinition {
        if (minX > maxX || minZ > maxZ) {
            throw new IllegalArgumentException("field corners are inverted");
        }
        int width = maxX - minX + 1;
        int depth = maxZ - minZ + 1;
        if (width < MIN_SIZE_M || depth < MIN_SIZE_M
            || width > MAX_SIZE_M || depth > MAX_SIZE_M) {
            throw new IllegalArgumentException("field size out of range: " + width + "x" + depth);
        }
        if (!Double.isFinite(originX) || !Double.isFinite(originZ)) {
            throw new IllegalArgumentException("field origin must be finite");
        }
        if (originMode == null || source == null) {
            throw new IllegalArgumentException("field origin mode and source are required");
        }
    }

    /** A field described by two opposite corners, centred origin. */
    public static TrainingFieldDefinition fromCorners(
        int x1, int z1, int x2, int z2, int topY, Source source
    ) {
        int minX = Math.min(x1, x2);
        int maxX = Math.max(x1, x2);
        int minZ = Math.min(z1, z2);
        int maxZ = Math.max(z1, z2);
        return new TrainingFieldDefinition(
            minX, minZ, maxX, maxZ, topY,
            (minX + maxX) / 2.0 + 0.5,
            (minZ + maxZ) / 2.0 + 0.5,
            OriginMode.CENTRE,
            source
        );
    }

    /**
     * A field described by the block the operator calls its centre plus its size
     * in metres (which is blocks). An even size cannot have a block centre, so the
     * rectangle is placed with the extra block on the negative side.
     */
    public static TrainingFieldDefinition fromCentreAndSize(
        int centerX, int centerZ, int widthM, int depthM, int topY, Source source
    ) {
        if (widthM < MIN_SIZE_M || depthM < MIN_SIZE_M
            || widthM > MAX_SIZE_M || depthM > MAX_SIZE_M) {
            throw new IllegalArgumentException("field size out of range: " + widthM + "x" + depthM);
        }
        int minX = centerX - widthM / 2;
        int minZ = centerZ - depthM / 2;
        return new TrainingFieldDefinition(
            minX, minZ, minX + widthM - 1, minZ + depthM - 1, topY,
            centerX + 0.5,
            centerZ + 0.5,
            OriginMode.CENTRE,
            source
        );
    }

    /** Footprint along the Minecraft X axis in metres. */
    public int widthM() {
        return maxX - minX + 1;
    }

    /** Footprint along the Minecraft Z axis in metres. */
    public int depthM() {
        return maxZ - minZ + 1;
    }

    /** The geometric centre of the field, in block-centre metres. */
    public double centreX() {
        return (minX + maxX) / 2.0 + 0.5;
    }

    public double centreZ() {
        return (minZ + maxZ) / 2.0 + 0.5;
    }

    /** True when the origin is the field centre, which is the default. */
    public boolean isCentred() {
        return originMode == OriginMode.CENTRE;
    }

    /**
     * The field centre relative to the origin, in metres, along the Minecraft X
     * and Z axes.
     *
     * <p>Those are exactly the axes the main project's scene uses for the same
     * point (its world x is minus east and its world z is minus north, as is the
     * mod's {@link NedWorldTransform}), so the pair can be published as
     * {@code field_center_m} without another conversion.
     */
    public double[] centerOffsetM() {
        return new double[] {centreX() - originX, centreZ() - originZ};
    }

    /** The NED origin this field implies, one block above the surface layer. */
    public NedWorldTransform originTransform() {
        return new NedWorldTransform(
            originX,
            topY + ArenaOrigin.PAD_SURFACE_OFFSET_M,
            originZ,
            WorldScale.metresPerBlock());
    }

    /** The footprint in metres, which is what the monitoring side is told. */
    public double[] sizeM() {
        double scale = WorldScale.metresPerBlock();
        return new double[] {widthM() * scale, depthM() * scale};
    }

    /** The same field with its origin on the {@code minX}/{@code minZ} corner block. */
    public TrainingFieldDefinition withOriginAtCorner() {
        return withOrigin(minX + 0.5, minZ + 0.5, OriginMode.CORNER);
    }

    /** The same field with an explicitly named origin point, in block centres. */
    public TrainingFieldDefinition withOrigin(double x, double z, OriginMode mode) {
        return new TrainingFieldDefinition(
            minX, minZ, maxX, maxZ, topY, x, z, mode, source);
    }

    /** The same field with another source label. */
    public TrainingFieldDefinition withSource(Source newSource) {
        return new TrainingFieldDefinition(
            minX, minZ, maxX, maxZ, topY, originX, originZ, originMode, newSource);
    }

    /** True when the block column {@code (x, z)} is inside the footprint. */
    public boolean containsBlock(int x, int z) {
        return x >= minX && x <= maxX && z >= minZ && z <= maxZ;
    }

    /**
     * Derives a field from marker blocks the operator placed, as {@code {x, y, z}}
     * triples.
     *
     * <p>Two diagonal corner markers are enough - the field is their bounding box,
     * and four corners give the same box - so a partly broken or partly placed set
     * still describes a field instead of failing. An optional centre marker names
     * the origin (which is how a room with its capture origin off centre is set up);
     * without one the origin is the centre of the box.
     *
     * <p>Returns null when there is nothing to derive from: one corner alone says
     * where a corner is but not how big the field is, and guessing a size would put
     * a field in the world that nobody asked for.
     *
     * <p>Takes plain coordinates rather than {@code BlockPos} so the geometric part
     * stays testable without the Minecraft classpath, which is where every other
     * rule in this record is checked too.
     */
    public static TrainingFieldDefinition fromMarkers(
        java.util.List<int[]> cornerMarkers,
        int[] centreMarker
    ) {
        if (cornerMarkers == null || cornerMarkers.size() < 2) {
            return null;
        }
        int minX = Integer.MAX_VALUE;
        int maxX = Integer.MIN_VALUE;
        int minZ = Integer.MAX_VALUE;
        int maxZ = Integer.MIN_VALUE;
        int topY = Integer.MAX_VALUE;
        for (int[] corner : cornerMarkers) {
            if (corner == null || corner.length < 3) {
                return null;
            }
            minX = Math.min(minX, corner[0]);
            maxX = Math.max(maxX, corner[0]);
            minZ = Math.min(minZ, corner[2]);
            maxZ = Math.max(maxZ, corner[2]);
            // The field plane is the lowest marked layer, matching what the
            // coordinate commands do when their two corners differ in Y.
            topY = Math.min(topY, corner[1]);
        }
        if (maxX - minX + 1 > MAX_SIZE_M || maxZ - minZ + 1 > MAX_SIZE_M) {
            return null;
        }
        TrainingFieldDefinition field =
            fromCorners(minX, minZ, maxX, maxZ, topY, Source.MARKERS);
        if (centreMarker == null || centreMarker.length < 3) {
            return field;
        }
        return field.withOrigin(
            centreMarker[0] + 0.5,
            centreMarker[2] + 0.5,
            OriginMode.EXPLICIT
        );
    }

    /** Human-readable summary for chat output; ASCII only. */
    public String describe() {
        return String.format(
            java.util.Locale.ROOT,
            "%dx%d m at x[%d..%d] z[%d..%d] y=%d, centre=(%.1f, %.1f), origin=(%.1f, %.1f) %s, source=%s",
            widthM(), depthM(), minX, maxX, minZ, maxZ, topY,
            centreX(), centreZ(), originX, originZ, originMode, source
        );
    }
}
